version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-partitions
    versions:
    - 1.424.0
    - 1.425.0
    - 1.426.0
    - 1.427.0
    - 1.428.0
    - 1.429.0
    - 1.430.0
    - 1.431.0
    - 1.431.1
    - 1.432.0
    - 1.433.0
    - 1.434.0
    - 1.435.0
    - 1.436.0
    - 1.437.0
    - 1.438.0
    - 1.439.0
    - 1.440.0
    - 1.441.0
    - 1.442.0
    - 1.443.0
    - 1.444.0
    - 1.445.0
    - 1.446.0
    - 1.447.0
  - dependency-name: stripe
    versions:
    - 5.29.1
    - 5.30.0
    - 5.31.0
  - dependency-name: bootsnap
    versions:
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: codecov
    versions:
    - 0.4.3
    - 0.5.0
    - 0.5.1
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: nio4r
    versions:
    - 2.5.5
  - dependency-name: puma
    versions:
    - 5.2.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: electron-to-chromium
    versions:
    - 1.3.657
    - 1.3.659
    - 1.3.661
    - 1.3.662
    - 1.3.663
    - 1.3.664
    - 1.3.665
    - 1.3.666
    - 1.3.667
    - 1.3.669
    - 1.3.671
    - 1.3.673
    - 1.3.674
    - 1.3.678
    - 1.3.680
    - 1.3.681
    - 1.3.683
    - 1.3.684
    - 1.3.685
    - 1.3.687
    - 1.3.689
    - 1.3.690
    - 1.3.691
    - 1.3.692
    - 1.3.693
    - 1.3.695
    - 1.3.703
    - 1.3.708
    - 1.3.710
    - 1.3.711
    - 1.3.712
    - 1.3.713
  - dependency-name: mobx
    versions:
    - 6.1.5
    - 6.1.6
    - 6.1.7
    - 6.1.8
    - 6.2.0
  - dependency-name: eslint-webpack-plugin
    versions:
    - 2.5.0
    - 2.5.1
    - 2.5.2
    - 2.5.3
  - dependency-name: dropzone
    versions:
    - 5.7.3
    - 5.7.5
    - 5.7.6
    - 5.8.0
    - 5.8.1
